// Generated by scripts/encrypt_creds.py — safe to commit.
export const ENC_CREDS = {
  salt: "Hmp/jGFwQBz0PFyvnJWcRg==",
  iv:   "08bQht9b8wrOqfyG",
  ct:   "fWCC/NEUBRffpZ5alb93Yv5xPn0fDxdGymKgTIGYPJ9GnMk7ujolVibcqsM2ZNXfwBxFkLoSrhe3ct7WZPcHsQlkF0FxW0a8bVdumpuleOJth+HDTjqA9ub+nQII8HUxafFctrLMmWPCJucCB1PWtwi5EN7rKuTkNej4OXc9cJvrTnTHer2bzp5JnQ6nrIzifQ==",
};
